### PR TITLE
Adding citations

### PR DESCRIPTION
**Pull request by javiferran**
Adding citations for the toolkit report and the "Information Flow Routes" paper.

### CODE REVIEW

**Review by mahnerak — APPROVED** [review]
Thanks @javiferran !

**Review by JoseIvanHernandez — COMMENTED** [review]
Commit

**Review by JoseIvanHernandez — COMMENTED** [review]
Commit

**Review by JoseIvanHernandez — COMMENTED** [review]
Commit

**Review by JoseIvanHernandez — COMMENTED** [review]
Commit

**Pull request merged**
